apiVersion: batch/v1
kind: CronJob
metadata:
  name: gitops-repo-pruner
spec:
  schedule: "0 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: gitops-repo-pruner
          containers:
          - name: gitops-repo-pruner
            image: gitops-repo-pruner:latest
            imagePullPolicy: Always
            command:
            - ./entrypoint.sh
            env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitops-pruner-token
                  key: token
                  optional: true
          restartPolicy: Never